[project]
name = "cherum"
version = "1.0.0"
description = "The basic blog app built in the Flask tutorial."
dependencies = [
    "flask[async]",
    "PyJWT",
    "influxdb_client"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
